eclipse-zenoh/zenoh-python

- Cargo.toml
- examples/zenoh/z_eval.py
- src/types.rs
- src/workspace.rs
- src/zenoh_net/mod.rs
- src/zenoh_net/session.rs
- src/zenoh_net/types.rs
This PR make zenoh-python to use the zenoh sync Rust API introduced by eclipse-zenoh/zenoh#95
> Port to recent zenoh sync Rust API

- examples/z_delete.py
- examples/z_eval.py
- examples/z_get.py
- examples/z_info.py
- examples/z_pub.py
- examples/z_pub_thr.py
- examples/z_pull.py
- examples/z_put.py
- examples/z_put_float.py
- examples/z_storage.py
- examples/z_sub.py
- examples/z_sub_thr.py
- src/lib.rs
`--listener` option has no effect in examples.
Cause: error in json format when adding options to the config.
> fix examples

- Cargo.lock
- Cargo.toml
- examples/asyncio/z_delete.py
- examples/asyncio/z_eval.py
- examples/asyncio/z_get.py
- examples/asyncio/z_get_parallel.py
- examples/asyncio/z_info.py
- examples/asyncio/z_pub.py
- examples/asyncio/z_put.py
- examples/asyncio/z_scout.py
- examples/asyncio/z_sub.py
- examples/z_get.py
- src/async_session.rs
- src/async_types.rs
- src/lib.rs
- src/session.rs
- src/types.rs
This PR adds an `AsyncSession` class defining all its methods (put, get, subscribe...)  as [asyncio](https://docs.python.org/3/library/asyncio.html) coroutines.
An `AsyncSession` object is returned calling the `zenoh.async_open()` coroutine.
Example of usage for a `put()`:
```python
import asyncio, zenoh
async def main():
s = await zenoh.async_open()
await s.put('/demo/example/zenoh-python-put', bytes('Put from asyncio Python!', encoding='utf8'))
asyncio.run(main())
```
Example of usage for a `subscribe()`:
```python
import asyncio, zenoh
from zenoh import Reliability, SubMode
async def callback(sample):
print("Received : {}".format(sample))
async def main():
s = await zenoh.async_open()
sub = await s.subscribe('/demo/example/**', callback,
reliability=Reliability.Reliable, …
```
> Asyncronous API for usage with asyncio

- .github/workflows/release.yml
Implement the solution described in https://github.com/eclipse-zenoh/zenoh-python/issues/64#issuecomment-1160507411
> Release action: add job to build an armv6l wheel (fix #64)

- Cargo.lock
- Cargo.toml
- examples/z_queryable.py
- examples/z_sub_thr.py
- src/closures.rs
- src/lib.rs
- zenoh/closures.py
Callbacks now start a PyThread upon receiving a value to avoid delaying message handover. Manually constructed zenoh.Closures may opt out of this behaviour.
> Make callbacks run concurrently

- examples/README.md
This is just to avoid confusing users any further.
> Remove asyncio mentions from the examples readme

- .github/workflows/ci.yml
Wake up CI runners when branches and pull requests are updated. So that the rule is aligned to the one used in zenoh and zenoh-c repos.
> Extend the triggering rules of CI

- Cargo.lock
- README.md
- examples/z_get.py
- examples/z_queryable.py
- src/enums.rs
- src/queryable.rs
- src/value.rs
- zenoh/queryable.py
- zenoh/value.py
Added:
- `is_ok` -> `bool` attribute to `Reply`
**Bonus**:
- add support for Errors in reply: added method `err(Value)` to `Query`
> feat(is-ok-in-reply): Adding `is_ok` attribute to `Reply` objects

- Cargo.lock
Automated synchronization of Cargo.lock and/or rust-toolchain.toml with Zenoh. This is necessary to ensure plugin ABI compatibility.
> Sync `Cargo.lock` and/or `rust-toolchain.toml` with Zenoh's

- .readthedocs.yml
- README.md
- docs/conf.py
- docs/requirements.txt
Resolves https://github.com/eclipse-zenoh/zenoh-python/issues/151.
Originally, the documentation build relied on the eclipse-zenoh-nightly PyPI package, which is not actively maintained currently. However, it is possible to build this crate from source in Read the Docs are they offer Rust toolchains.
> fix: Documentation build

- Cargo.lock
- Cargo.toml
- pyproject.toml
- With the version tag, we can use and build zenoh-python in the pyproject.toml from the other project.
- Remove unneeded dependencies and update Cargo.lock
> Add the version tag

- docs/index.rst
The python doc shows that you can have a / at the beginning of the key expression, but this create an error and apparently is not allowed. Here a PR to fix this 😄
> documentation remove first / at key expressions

- examples/z_pub.py
- examples/z_pub_thr.py
- examples/z_pull.py
- examples/z_queryable.py
- examples/z_storage.py
- examples/z_sub.py
- examples/z_sub_queued.py
- examples/z_sub_thr.py
- tests/examples_check.py
These changes remove reading from stdin for all examples, and align their behaviors and outputs across projects. Closes #144
This PR is part of an effort across currently active Zenoh projects. To maintain examples' implementations as close to each other as possible, any changes identified in other projects will be replicated in this PR. As such, **please do not merge these changes until all PRs are ready for merging**.
Related PRs:
- https://github.com/eclipse-zenoh/zenoh/pull/768
- https://github.com/eclipse-zenoh/zenoh-c/pull/255
- https://github.com/eclipse-zenoh/zenoh-cpp/pull/103
- https://github.com/eclipse-zenoh/zenoh-java/pull/45
- https://github.com/eclipse-zenoh/zenoh-kotlin/pull/47
- https://github.com/eclipse-zenoh/zenoh-pico/pull/359
> Align examples and remove reading from stdin

- pyproject.toml
According to [the official guideline](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration), `zip-safe` is obsolete and the options author/email are replaced by authors.
> Correct the syntax of pyproject.toml

- docs/requirements.txt
This PR fixes the readthedocs build failure in CI.
> Fix: force sphinx version to 7.2.6 for readthedocs build

- .github/workflows/release.yml
The existing command installs maturin 1.5 for the build-linux-armv6, instead of the version defined in dev-requirements.txt and the version used by the other jobs.
> fix: Install maturin according to `requirements-dev.txt`

- src/session.rs
Closes #180
Releasing GIL in Scout destructor prevents the deadlock.
> fix: fix scout deadlock

- .github/workflows/release.yml
upload-artifacts/v4 has a breaking change from v3, which requires the artifacts names to be unique. Fix #219
> fix: give unique name for artifacts

- README.md
- examples/README.md
Fix the lint error of markdown.
> Fix markdown format in README.

- .github/workflows/release.yml
See https://github.com/PyO3/maturin/pull/1620, `--universal2` has been deprecated
> fix: remove deprecated maturin arg

- .github/workflows/release.yml
See https://github.com/PyO3/maturin/pull/1620, `--universal2` has been deprecated
> fix: remove deprecated maturin arg (#241)

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- README.md
- docs/requirements.txt
- examples/README.md
@diogomatsubara can you double check my merge?
@Mallets
> Merge main into dev/1.0

- examples/z_get.py
Will use default config of consolidation (AUTO) to align with other implementations of `z_get`.
> Use default consolidation config in z_get example

- examples/z_delete.py
- examples/z_get.py
- examples/z_info.py
- examples/z_ping.py
- examples/z_pong.py
- examples/z_pub.py
- examples/z_pub_thr.py
- examples/z_pull.py
- examples/z_put.py
- examples/z_queryable.py
- examples/z_scout.py
- examples/z_storage.py
- examples/z_sub.py
- examples/z_sub_queued.py
- examples/z_sub_thr.py
- src/lib.rs
- zenoh/__init__.pyi
Use `init_log_from_env_or("error")` instead of `try_init_log_from_env` in examples.
> Use init_log_from_env_or for examples

- ci/scripts/bump-and-tag.bash
- requirements-dev.txt
On development builds, use a PEP-440 compatible version, since maturin>1 requires stricter version checking.
Here you can see the failure with the semver version: https://github.com/eclipse-zenoh/zenoh-python/actions/runs/10894902155/job/30232339459
I ran a build here: https://github.com/eclipse-zenoh/zenoh-python/actions/runs/10897575950 with the edited version string and maturin builds correctly.
> fix: edit version for devel builds

- examples/z_bytes.py
- examples/z_delete.py
- examples/z_get.py
- examples/z_pull.py
- examples/z_put.py
- examples/z_queryable.py
- examples/z_storage.py
- examples/z_sub.py
- examples/z_sub_queued.py
- src/bytes.rs
- tests/examples_check.py
- tests/test_serializer.py
- zenoh/__init__.py
- zenoh/__init__.pyi
> docs: add z_bytes example

- .github/workflows/ci.yml
- src/lib.rs
- src/query.rs
- src/session.rs
- src/time.rs
- src/utils.rs
- zenoh/__init__.pyi
> chore: API alignment

- tests/examples_check.py
See https://github.com/eclipse-zenoh/zenoh-python/actions/runs/11156791552/job/31009996613
I managed to reproduce this locally and by waiting longer I got better tests results. Similar to https://github.com/ZettaScaleLabs/zenoh-tests/pull/67
> fix: wait longer on z_sub example

- .github/workflows/ci.yml
- requirements-dev.txt
- tests/examples_check.py
Attempt to fix racy behaviour in tests like: https://github.com/eclipse-zenoh/zenoh-python/actions/runs/11158739052/job/31015765836
This started as small fix to increase sleep times and ended up with a re-org of the examples test code.
> fix: wait longer after z_put

- src/query.rs
> fix: fix `Parameters.__iter__` not returning an iterator

- src/handlers.rs
> feat: add warning if drop-callback is passed with a tuple

- .github/workflows/ci.yml
Resolves #356
since https://github.com/isort/isort-action/issues/94 resolved, ci check job runner can be put back to ubuntu-latest
> chore: revert ci check back to ubuntu-latest after isort fix

- docs/index.rst
- docs/stubs_to_sources.py
- tests/stubs_check.py
- zenoh/__init__.py
- zenoh/__init__.pyi
> tag unstable functionality

- examples/z_queryable.py
- src/handlers.rs
- src/query.rs
- src/utils.rs
- tests/examples_check.py
- zenoh/__init__.pyi
> Query context manager

- ci/scripts/bump-and-tag.bash
remove -dev suffix from version, since that's not used anymore. This should allow git describe tag to work with maturin
See https://github.com/eclipse-zenoh/zenoh-python/actions/runs/13960108853/job/39079789767#step:3:192
> fix: update bump and tag for dev releases

- src/handlers.rs
- src/utils.rs
Only the `IntoPython` bound is important, the rest was there to reinforce the typing, but it's not needed at all, and it prevented to use objects not implementing `IntoRust` (which will be the case when `Query` will use `option_wrapper`)
> remove useless `IntoRust` bound in handlers system

- README.md
> document how to enable compilation feature in README

- examples/common/common.py
The socket address contains colon which causes the below exception:
```
[key, value] = c.split(":")
ValueError: too many values to unpack (expected 2)
```
This PR passing `maxsplit` on split to fix the error.
> fix: can't pass socket address in cfg on python examples

- docs/conf.py
- docs/index.rst
- zenoh/ext.pyi
add docs for z_serialize and z_deserialize functions
> add docs for z_serialize and z_deserialize functions
