Cargo.lock
examples/asyncio/z_delete.py
examples/asyncio/z_eval.py
examples/asyncio/z_get.py
examples/asyncio/z_get_parallel.py
examples/asyncio/z_info.py
examples/asyncio/z_pub.py
examples/asyncio/z_put.py
examples/asyncio/z_sub.py
examples/z_delete.py
examples/z_eval.py
examples/z_get.py
examples/z_info.py
examples/z_pub.py
examples/z_pub_thr.py
examples/z_pull.py
examples/z_put.py
examples/z_put_float.py
examples/z_storage.py
examples/z_sub.py
examples/z_sub_thr.py
src/encoding.rs
src/lib.rs
src/session.rs
src/types.rs

Sister PR for eclipse-zenoh/zenoh#214

Sister PR for eclipse-zenoh/zenoh#214

---

Cargo.lock
examples/asyncio/z_get.py
examples/asyncio/z_get_parallel.py
examples/z_get.py
src/async_session.rs
src/lib.rs
src/session.rs
src/types.rs

Following eclipse-zenoh/zenoh#233

Renamed Reply.data as Reply.sample

---

zenoh/session.py

Sister PR: https://github.com/eclipse-zenoh/zenoh/pull/320.

Don't expose local_routing which is unstable

---

Cargo.lock
examples/z_pub.py
src/session.rs
zenoh/session.py

until we find a way to expose unstable features well in python

remove unstable aspects from bindings 

---

zenoh/queryable.py

Fix Queryable.decode_parameters

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
docs/conf.py
docs/requirements.txt
examples/z_get.py
examples/z_queryable.py
src/queryable.rs
src/session.rs
zenoh/queryable.py
zenoh/session.py
zenoh/value.py

As defined in https://github.com/eclipse-zenoh/roadmap/blob/3df8f147ae7c9586d452bc38e83497d52d71eade/rfcs/ALL/Query%20Payload.md
To be merged after:

Add support for query payload

---

zenoh/keyexpr.py

This solves the footgun @gabrik encountered last week

Make KE more ergonomic by converting strings when comparing

---

Cargo.lock
Cargo.toml

Sister PR: https://github.com/eclipse-zenoh/zenoh/pull/506

Align with zid branch

---

.github/workflows/ci.yml
tests/test_session.py

A first try for https://github.com/eclipse-zenoh/zenoh-python/issues/103

Add get/queryable into session unit test

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/lib.rs
src/queryable.rs
src/session.rs

To be merged after: https://github.com/eclipse-zenoh/zenoh/pull/604
Before merging, the PR should point to master.
Sister PR: https://github.com/eclipse-zenoh/zenoh-c/pull/204

Feature cleanup

---

examples/z_put.py

fix(examples): fix commented parts of z_put.py

---

.github/workflows/release.yml

[See this run failure.](https://github.com/eclipse-zenoh/zenoh-python/actions/runs/8793376928/job/24131166619)

fix: Create virtual environment for armv6 build

---

examples/z_ping.py
examples/z_pong.py

test: add z_ping/z_pong examples

---

src/queryable.rs
src/value.rs
tests/test_session.py
zenoh/queryable.py
zenoh/value.py

relates to https://github.com/eclipse-uprotocol/up-client-zenoh-python/pull/3

fix: make attachment API more similar to dict API

---

src/session.rs
zenoh/session.py

The PR is mainly for
* Support timeout for Zenoh query, just like [Rust one](https://github.com/eclipse-zenoh/zenoh/blob/b8dd01d6ce05f851f33497e8d899df308d315afb/examples/examples/z_get.rs#L37)
* ~~Update README format~~

Support timeout in Zenoh query

---

src/bytes.rs
src/encoding.rs
src/lib.rs
tests/test_serializer.py
zenoh/__init__.pyi
zenoh/handlers.pyi

fix: fix serializers

---

examples/z_queryable.py
examples/z_sub_thr.py
src/handlers.rs
src/lib.rs
src/scouting.rs
src/session.rs
zenoh/__init__.pyi
zenoh/handlers.pyi

feat: make callbacks indirect by default

---

Cargo.lock
examples/z_delete.py
examples/z_get.py
examples/z_info.py
examples/z_ping.py
examples/z_pong.py
examples/z_pub.py
examples/z_pub_thr.py
examples/z_pull.py
examples/z_put.py
examples/z_queryable.py
examples/z_scout.py
examples/z_storage.py
examples/z_sub.py
examples/z_sub_queued.py
examples/z_sub_thr.py
src/lib.rs
src/logging.rs
tests/test_session.py
zenoh/__init__.pyi

feat: improve logging

---

.github/workflows/ci.yml

ci: execute trivial checks separately from testing

---

Cargo.lock
src/bytes.rs
src/encoding.rs

Align Python bindings with recent changes introduced by https://github.com/eclipse-zenoh/zenoh/pull/1174

Add encoding types

---

src/config.rs
src/session.rs
zenoh/__init__.pyi

fix: makes `Session.open` config argument mandatory

---

Cargo.lock
src/handlers.rs

See https://github.com/eclipse-zenoh/zenoh/pull/1504.

Sync lockfile with Zenoh `e9f3b37` from `2024-10-08`

---

examples/README.md

fix examples README outdated args

---

examples/z_delete.py
examples/z_get_liveliness.py
examples/z_liveliness.py
examples/z_ping.py
examples/z_pong.py
examples/z_pub.py
examples/z_pull.py
examples/z_put.py
examples/z_put_float.py
examples/z_sub.py
examples/z_sub_liveliness.py

* remove the space line after the with statement
* remove unused json import

style: fix few minor code style issues on examples 

---

.github/workflows/ci.yml

Fix https://github.com/eclipse-zenoh/zenoh-python/actions/runs/15179421979/job/42685690466

ci: install rust components

---

src/ext.rs
src/lib.rs
src/pubsub.rs
src/query.rs
src/sample.rs
src/session.rs
zenoh/__init__.pyi
zenoh/ext.pyi

add locality support;
add timestamp options for put/query;
resolves #515 
resolves #552

add locality and timestamp options
